use flutter_rust_bridge::frb;
use log::info;
use preferences::AppInfo;

use crate::imp::{AppPrefs, APP_PREFS, IS_INITIALIZED};
use simple_logger::SimpleLogger;

pub fn init(app_id: String, author: String) {
    {
        let mut is_initialized = IS_INITIALIZED.lock().unwrap();
        if *is_initialized {
            return;
        }
        *is_initialized = true;
    }
    SimpleLogger::new().init().unwrap();
    info!("Initializing flutter_preference");
    // Default utilities - feel free to customize
    flutter_rust_bridge::setup_default_user_utils();
    // keys that are generated by the user
    let app_id = Box::leak(Box::new(app_id));
    let author = Box::leak(Box::new(author));
    let app_info = AppInfo {
        name: app_id,
        author,
    };
    APP_PREFS.lock().unwrap().replace(AppPrefs::new(app_info));
    info!("flutter_preference initialized");
}

pub fn set_string(key: String, value: String) -> () {
    info!("Setting key: {} with value: {}", key, value);
    APP_PREFS
        .lock()
        .unwrap()
        .as_ref()
        .expect("flutter_preference was not initialized")
        .set_string(key, value);
}

pub fn get_string(key: String) -> Option<String> {
    info!("Getting key: {}", key);
    APP_PREFS
        .lock()
        .unwrap()
        .as_ref()
        .expect("flutter_preference was not initialized")
        .get_string(key)
}
