[package]
name = "flutter_preferences"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
lazy_static = "1.5.0"
log = "0.4.25"
preferences = "2.0.0"
simple_logger = "5.0.0"
