// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `APP_PREFS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppInfo>>
abstract class AppInfo implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppPrefs>>
abstract class AppPrefs implements RustOpaqueInterface {
  AppInfo get appInfo;

  MutexPreferencesMapString get userKeys;

  set appInfo(AppInfo appInfo);

  set userKeys(MutexPreferencesMapString userKeys);

  Future<String?> getString({required String key});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AppPrefs> newInstance({required AppInfo appInfo}) =>
      RustLib.instance.api.crateApiImpAppPrefsNew(appInfo: appInfo);

  Future<void> setString({required String key, required String value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Mutex < PreferencesMap < String > >>>
abstract class MutexPreferencesMapString implements RustOpaqueInterface {}
